language: node_js
node_js:
  - "lts/*"
script: npm run website-dist
branches:
  only:
    - stable
deploy:
  provider: pages
  local_dir: website/dist
  file:
    - bundle.js
    - duxtree.css
    - duxtree.png
    - index.html
    - styles.css
  fqdn: www.duxtree.org
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: stable
