language: node_js
node_js:
  - "lts/*"
script: npm run website-dist
branches:
  only:
    - stable
deploy:
  provider: pages
  local-dir: website/dist
  fqdn: www.duxtree.org
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: stable
